const BAD_REQUEST_STATUS_CODE = 400;
const PAGE_NOT_FOUND = 404;
const SERVER_MALFUNCTION = 500;
const REQUEST_COMPLETED_SUCCESSFULLY = 200;
const YOUR_DATA_IS_CREATED = 201;
const UNAUTHORIZED_ACCESS = 401;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  SERVER_MALFUNCTION,
  PAGE_NOT_FOUND,
  REQUEST_COMPLETED_SUCCESSFULLY,
  YOUR_DATA_IS_CREATED,
  UNAUTHORIZED_ACCESS,
};
